spring:
  profiles: 
    active: localdb

server:
  port: 18090
  servlet:
    context-path: /auth-server

# To enabled Hystrix in Feign
feign.hystrix.enabled: true

logging:
  level:
    root: INFO
    com.psys.hobb: DEBUG
    org:
      springframework:
        web:
          servlet:
            DispatcherServlet: TRACE
            mvc.method.annotation.ServletInvocableHandleMethod: TRACE
      hibernate:
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
              BasicExtractor: TRACE
        engine:
          QueryParameters: TRACE
          query:
            HQLQueryPlan: TRACE